version: '3.3'

services:
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - ./db/scripts:/docker-entrypoint-initdb.d/
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=segwaredb

    clientdb:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1

    server:
        build:
            dockerfile: ./Dockerfile
            context: ./server
        ports:
            - "8080:8080"
        links:
            - db
        depends_on:
            - db

    client:
        build:
            dockerfile: ./Dockerfile
            context: ./client
        ports:
            - "3000:3000"
        links:
            - server
        depends_on:
            - server
